---
- name: "Test de connexion SSH via Shell"
  hosts: switch-tete
  gather_facts: no
  connection: local  # On exécute la commande DEPUIS le conteneur AWX

  tasks:
    - name: Tenter une connexion SSH directe via le client système
      ansible.builtin.shell: >
        sshpass -p "{{ ansible_password | default(ansible_ssh_pass) }}" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o KexAlgorithms=+diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1 -o HostKeyAlgorithms=+ssh-rsa {{ ansible_user | default(ansible_ssh_user) }}@{{ ansible_host }} "show version"
      register: ssh_test

    - name: Afficher le résultat de la connexion
      ansible.builtin.debug:
        var: ssh_test.stdout_lines
