---
- name: "Test de connexion SSH avec le Switch Cisco"
  hosts: switch-tete
  gather_facts: no
  connection: ansible.netcommon.network_cli

  tasks:
    - name: Envoyer une commande de test au switch
      cisco.ios.ios_command:
        commands:
          - show version | include System image file
      register: ssh_test

    - name: Afficher le résultat de la connexion
      ansible.builtin.debug:
        msg: "Connexion SSH réussie ! Réponse du switch : {{ ssh_test.stdout[0] }}"
